#! /bin/sh

sxhkd &
remaps &
setbg &
picom &
dunst &
xset r rate 300 50 &
unclutter &

$HOME/.config/polybar/launch.sh
# $HOME/.screenlayout/single4k.sh

bspc monitor eDP-1 -d 1 2 3 4 5
bspc monitor HDMI-1 -d 6 7 8 9 0

bspc config border_width         2
bspc config window_gap           2
bspc config top_padding         23
bspc config right_padding        0
bspc config left_padding         0
bspc config border_radious       1

bspc config split_ratio          0.5
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config paddingless_monocle  true
bspc config pointer_motion_interval 7
bspc config automatic_scheme eDP-1
bspc config pointer_modifier     mod4
bspc config click_to_focus       true
bspc config focus_follows_pointer true
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a Screenkey manage=off
bspc rule -a Steam desktop='^5'

bspc rule -a Sxiv state=floating follow=on
bspc rule -a XenonTrade stat=floating desktop='^6'
bspc rule -a Ripcord desktop='^3'
bspc rule -a discord desktop='^3'
bspc rule -a TelegramDesktop desktop='^3'
bspc rule -a ide desktop='^4' state=tiled
bspc rule -a gamehub desktop='^5'

# Scratch Pad
# scratch &
bspc rule -a scratchterm sticky=on state=floating hidden=on locked=on
