[module/updates]
type = custom/script

; Available tokens:
;   %counter%
; Command to be executed (using "/usr/bin/env sh -c [command]")
exec = ~/.config/polybar/scripts/updates.sh

; Conditional command that, if defined, needs to exit successfully
; before the main exec command is invoked.
; Default: ""
;;exec-if = ""

; Will the script output continous content?
; Default: false
tail = true

; Seconds to sleep between updates
; Default: 2 (0 if `tail = true`)
interval = 5

; Available tags:
;   <output> - deprecated
;   <label> (default)
;;format = <label>
format-background = ${color.mf}
format-underline = ${color.bg}
format-overline = ${color.bg}
format-padding = 2
format-margin = 1

; Available tokens:
;   %output%
; Default: %output%
;;label = %output:0:15:...%

; Available tokens:
;   %counter%
;   %pid%
;
; "click-(left|middle|right)" will be executed using "/usr/bin/env sh -c [command]"
click-left = ~/.config/polybar/scripts/lupdates &
;;click-middle = ~/.config/polybar/scripts/lupdates &
;;click-right = ~/.config/polybar/scripts/lupdates &
;;double-click-left = echo double left %counter%
;;double-click-middle = echo double middle %counter%
;;double-click-right = echo double right %counter%

; Available tokens:
;   %counter%
;   %pid%
;
; "scroll-(up|down)" will be executed using "/usr/bin/env sh -c [command]"
;;scroll-up = echo scroll up %counter%
;;scroll-down = echo scroll down %counter%

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
[module/pulseaudio-control]
type = custom/script
tail = true
label=%output%
; format-underline = ${color.blue}

exec = ~/.config/polybar/scripts/pulseaudio-control.bash listen
click-right = exec $TERMINAL -e pulsemixer &
click-left = ~/.config/polybar/scripts/pulseaudio-control.bash togmute
click-middle = ~/.config/polybar/scripts/pulseaudio-control.bash next-sink
scroll-up = ~/.config/polybar/scripts/pulseaudio-control.bash up
scroll-down = ~/.config/polybar/scripts/pulseaudio-control.bash down

label-foreground = ${color.fg}

format-background = ${color.mf}
format-underline = ${color.bg}
format-overline = ${color.bg}
format-padding = 2
format-margin = 1
